// Authentcation
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT_USER = "LOGOUT_USER";

//Profile
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_MY_PROFILE = "FETCH_MY_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";

//Activities
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const FETCH_CATEGORY_ACTIVITIES = "FETCH_CATEGORY_ACTIVITIES";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";

export const ACTIVITY_DETAILS = "ACTIVITY_DETAILS";
export const CATCH_CATEGORY_ID = "CATCH_CATEGORY_ID";

//Activity CRUD
export const CREATE_ACTIVITY = "CREATE_ACTIVITY";
export const RESET_ACTIVITY_ADD = "RESET_ACTIVITY_ADD";
export const UPDATE_ACTIVITY = "UPDATE_ACTIVITY";
export const DELETE_ACTIVITY = "DELETE_ACTIVITY";

//Invite
export const CREATE_INVITE = "CREATE_INVITE";

//Error
export const ERROR = "ERROR";
